---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: content

tabs:
  - name: Developer Hub
    url: 'https://backstage-developer-hub-developer-hub.${DOMAIN}'
  - name: Gitea
    url: 'https://gitea-gitea.${DOMAIN}'
  - name: DevSpaces
    url: 'https://devspaces.${DOMAIN}'
  - name: OpenShift Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: Terminal
    url: '/terminal/'
